import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import SwapForm from "../components/SwapForm";


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Token Swap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SwapForm />
        {/* <div className="col col-md-6 offset-md-3" id="window">
          <h4>Swap</h4>
          <div id="form">
            <div className="swapbox">
              <div
                className="swapbox_select token_select"
                id="from"
                onClick={modalHandler}
              >
                {fromToken.symbol ? fromToken.symbol : "SELECT A TOKEN"}
              </div>
              <div className="swapbox_select">
                <input
                  className="number form-control"
                  placeholder="amount"
                  id="fromAmount"
                  value={fromAmount}
                  onChange={setAmountHandler}
                />
              </div>
            </div>
            <div className="swapbox">
              <div
                className="swapbox_select token_select"
                id="to"
                onClick={modalHandler}
              >
                {toToken.symbol ? toToken.symbol : "SELECT A TOKEN"}
              </div>
              <div className="swapbox_select">
                <input
                  className="number form-control"
                  placeholder="amount"
                  id="toAmount"
                  value={toAmount}
                  onChange={setAmountHandler}
                />
              </div>
            </div>
            <div className="gas_estimate_label">
              Estimated Gas: <span id="gas_estimate"></span>
            </div>
            <button
              // disabled
              className="btn btn-large btn-primary btn-block"
              id="swap_button"
              onClick={trySwap}
            >
              Swap
            </button>
          </div>
        </div>

        {modalOpen && (
          <Modal
            tokens={tokenList}
            selectId={selectId}
            setFromToken={setFromToken}
            setToToken={setToToken}
          />
        )} */}
        {/* {modalOpen && <DynamicModal tokens={tokenList} />} */}
        {/* <Modal
          tokens={tokenList}
          selectId={selectId}
          setFromToken={setFromToken}
          setToToken={setToToken}
        /> */}
      </main>
    </div>
  );
};

export default Home;
